server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*))\|
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # System logs
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog

  # Application logs from services
  - job_name: gateway
    static_configs:
      - targets:
          - localhost
        labels:
          job: gateway
          service: gateway
          __path__: /var/log/gateway/*.log

  - job_name: shortener
    static_configs:
      - targets:
          - localhost
        labels:
          job: shortener
          service: shortener
          __path__: /var/log/shortener/*.log

  - job_name: redirector
    static_configs:
      - targets:
          - localhost
        labels:
          job: redirector
          service: redirector
          __path__: /var/log/redirector/*.log

  - job_name: analytics
    static_configs:
      - targets:
          - localhost
        labels:
          job: analytics
          service: analytics
          __path__: /var/log/analytics/*.log
